### ISSUE TITLE
behaviour of unmatched - ADD THIS TO PARKING LOT

### ISSUE THREAD

**Issue by shosein** [EduShareOntario/jobCollectionService#32]
[Unmatched.docx](https://github.com/EduShareOntario/jobCollectionService/files/178188/Unmatched.docx)

**Comment by moonrockfamily** [comment]
## Possible solution:
**Rule:** Prohibit _**review**_ when the transcript is NOT _pending review_
**UI:** Review button is omitted from the view
**Data integrity:** back-door attempts are prohibited

**Comment by shosein** [comment]
We like this approach.  We would like this tackled AFTER this week so that we have a bit of stability before we make new changes.
