### ISSUE TITLE
SVATREQ - Notes not populating in Prod

### ISSUE THREAD

**Issue by shosein** [EduShareOntario/jobCollectionService#37]
This worked in test however does not work in prod.  
![svatreq - march 29](https://cloud.githubusercontent.com/assets/15947632/14114764/5cc31c0e-f5a6-11e5-9b2c-ed58e693eb72.JPG)

**Comment by mdwmax** [comment]
That record is edi sourced  which is before we were live.  Have confirmed that the records are being written out to the notes table.

![edisource](https://cloud.githubusercontent.com/assets/3621102/14115876/fac82184-f5aa-11e5-93b3-8ccd625d9cc1.png)
![notes](https://cloud.githubusercontent.com/assets/3621102/14115875/fac5baac-f5aa-11e5-8018-138bf9cb4705.png)

**Comment by shosein** [comment]
Charlotte checked the first 4 records.  Only the first one has a note...she's checking a few more.  Perhaps this is related to the other SVATREQ issue where we get an error indicating that "updates are not allowed".

[SVATREQ Notes.docx](https://github.com/EduShareOntario/jobCollectionService/files/193872/SVATREQ.Notes.docx)
