### ISSUE TITLE
Missing transcripts in view queue

### ISSUE THREAD

**Issue by shosein** [EduShareOntario/jobCollectionService#38]
Hi Charlotte,
So I’ve been monitoring the view queue and there are currently 4 transcripts where there is a request sitting in eTMS but nothing in the view queue (I’ve checked all filter).

Would Todd maybe be able to take a look?

Shane Longstreet 20160331114641 (Mar 31)
Sarah Turner 20160331114650 ( Mar 31)
Kyle Nutbrown 20160402609278 (April 2)
Lindsay Jennings C20160403609347 ( April 3)

Also, no errors in the email account.

**Comment by moonrockfamily** [comment]
Figured out the mystery!  These transcripts were processed when the Elastic Search service was stopped.  I restarted the Transcript review/job collection service to get the documents added to the Elastic Search service and confirmed they are showing at https://api.georgiancollege.ca/transcript/review
